version: 0.1
phases:
  install:
    commands:
      - node -v
      - npm install serverless
      - npm install serverless-sam
      - serverless sam export --output ./samTemplate.yaml
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket homex-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
