version: 0.1
phases:
  install:
    commands:
      - npm install serverless -g
      - npm install serverless-sam --save-dev
      - npm install serverless-domain-manager --save-dev
      - serverless sam export --output ./samTemplate.yaml
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket saugata-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
