service: helloworld

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  
plugins:
  - serverless-sam

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true